package consts

// load
const (
	LOADER_JSON  = "JSON"
	LOADER_YAML  = "YAML"
	LOADER_DBLD  = "DBLD"
	LOADER_MYSQL = "MYSQL"
	LOADER_MONGO = "MONGO"
	LOADER_EMBED = "EMBED"
)

// ENGINE
const (
	SEARCH_DBMYSQL = "MYSQLDB"
	SEARCH_MONGODB = "MONGODB"
	SEARCH_ELASTIC = "ELASTIC"
	SEARCH_MEMORY  = "MEMORY"
)

// PARSER
const (
	PARSER_SEARCH = "SEARCH"
	PARSER_WRITER = "WRITER"
)
