package consts

const (
	VISIBLE_NONE = "NONE"
	VISIBLE_SHOW = "SHOW"
	VISIBLE_HIDE = "HIDE"
)

const (
	EDITABLE_EMPTY  = ""
	EDITABLE_NEVER  = "NEVER"
	EDITABLE_ALWAYS = "ALWAYS"
	EDITABLE_INSERT = "INSERT"
	EDITABLE_UPDATE = "UPDATE"
	EDITABLE_UPSERT = "UPSERT"
)

const (
	DISABLED_EMPTY  = ""
	DISABLED_NEVER  = "NEVER"
	DISABLED_ALWAYS = "ALWAYS"
	DISABLED_INSERT = "INSERT"
	DISABLED_UPDATE = "UPDATE"
	DISABLED_UPSERT = "UPSERT"
)

const (
	GROUP_BASIC = "basic"

	FIELD_UUKEY = "basic.uukey"
	FIELD_UTIME = "basic.utime"
	FIELD_STATE = "basic.state"
	FIELD_UTERM = "basic.uterm"
	FIELD_UWEEK = "basic.uweek"

	// 关联字段
	REFER_MODEL = "model"
	REFER_VALUE = "refer"
	FIELD_MODEL = "basic.model"
	FIELD_REFER = "basic.refer"

	FIELD_CORP_ID = "basic.corp_id"
	FIELD_TEAM_ID = "basic.team_id"
	FIELD_USER_ID = "basic.user_id"
)

const (
	GTYPE_FLATTEN = "FLATTEN"
	GTYPE_GROUPED = "GROUPED"
)
const (
	DTYPE_SERIALNO = "SERIALNO"
	DTYPE_KEYWORDS = "KEYWORDS"
	DTYPE_LONGTEXT = "LONGTEXT"
	DTYPE_RICHTEXT = "RICHTEXT"
	DTYPE_SUBJECT  = "SUBJECT"
	DTYPE_INTEGER  = "INTEGER"
	DTYPE_BOOLEAN  = "BOOLEAN"
	DTYPE_TINYINT  = "TINYINT"
	DTYPE_LONGINT  = "LONGINT"
	DTYPE_EXPENSE  = "EXPENSE"
	DTYPE_DECIMAL  = "DECIMAL"
	DTYPE_SCALED   = "SCALED"
	DTYPE_ONLYDATE = "ONLYDATE"
	// DTYPE_ONLYTIME = "ONLYTIME"
	DTYPE_DATETIME = "DATETIME"
	DTYPE_ALL_FILE = "ALL_FILE"
	DTYPE_DOC_FILE = "DOC_FILE"
	DTYPE_IMG_FILE = "IMG_FILE"
	DTYPE_LOCATION = "LOCATION"

	// 扩展类型
	DTYPE_X_PHONE = "X-PHONE"
	DTYPE_X_EMAIL = "X-EMAIL"

	// 直接 copy
	DTYPE_OPTIONAL = "OPTIONAL"
	DTYPE_WORKFLOW = "WORKFLOW"
	DTYPE_RELATION = "RELATION"
)

const (
	FTYPE_SERIALNO = "SERIALNO"
	FTYPE_SUBJECT  = "SUBJECT"
	FTYPE_SOCIALS  = "SOCIALS"
	FTYPE_STRINGS  = "STRINGS"
	FTYPE_NUMERIC  = "NUMERIC"
	FTYPE_EXPENSE  = "EXPENSE"
	FTYPE_LOCATION = "LOCATION"
	FTYPE_OPTIONAL = "OPTIONAL"
	FTYPE_WORKFLOW = "WORKFLOW"
	FTYPE_DATETIME = "DATETIME"
	FTYPE_RELATION = "RELATION"
	FTYPE_UPLOADS  = "UPLOADS"
	FTYPE_BOOLEAN  = "BOOLEAN"
	FTYPE_TINYINT  = "TINYINT"
)
