package consts

const (
	DATABASE_MYSQL    = "DATABASE_MYSQL"
	DATABASE_MONGO    = "DATABASE_MONGO"
	DATABASE_POSTGRES = "DATABASE_POSTGRES"
	DATABASE_SQLITE   = "DATABASE_SQLITE"
	DATABASE_REDIS    = "DATABASE_REDIS"
	ELASTIC_SEARCH = "ELASTIC_SEARCH"
	OBJECT_EMBEDFS = "OBJECT_EMBEDFS"

	DB_TABLE_NAMES = "DB_TABLE_NAMES"

	SLOW_THRESHOLD = "SLOW_THRESHOLD"
)
