package consts

const (
	ACTION_DELETE = "DELETE"
	ACTION_UPDATE = "UPDATE"
	ACTION_UPSERT = "UPSERT"
	ACTION_INSERT = "INSERT"
	ACTION_APPEND = "APPEND"
	ACTION_REMOVE = "REMOVE"
	ACTION_IMPORT = "IMPORT"
	ACTION_EXPORT = "EXPORT"
)

const (
	STATE_NORMAL = 1
	STATE_DELETE = 0

	STATE_ENABLE   = 1
	STATE_DISABLED = 0
)
