package consts

// query
const (
	// 字符串
	LOGIC_EQUALSTO = "EQ"
	LOGIC_NOTEQUAL = "NE"

	LOGIC_CONTAINS = "HAS"
	LOGIC_INCLUDES = "IN"
	LOGIC_STR_LIKE = "LIKE"
	// 数值
	LOGIC_LESTHAN = "LT"
	LOGIC_LESS_EQ = "LE"
	LOGIC_GREATER = "GT"
	LOGIC_GRAT_EQ = "GE"
	LOGIC_BETWEEN = "BTW"
	LOGIC_RECENT  = "RCT"
	LOGIC_FUTURE  = "FTR"
	// 关系
	LOGIC_SUBOR  = "OR"
	LOGIC_SUBAND = "AND"
	LOGIC_SUBNOT = "NOT"
	LOGIC_SUBRAW = "RAW"

	LOGIC_VAL_NULL = "NIL"
	LOGIC_NOT_NULL = "NNL"

	// 自己可见
	LOGIC_MY_SCOPE = "MYS"

	// 结构
	LOGIC_EXISTS = "EXISTS"
	LOGIC_NESTED = "NESTED"
)
