package consts

// SCENE
const (
	SCENE_SHEET  = "SHEET"
	SCENE_MERGE  = "MERGE"
	SCENE_INPUT  = "INPUT"
	SCENE_REFER  = "REFER"
	SCENE_DIGEST = "DIGEST"
	SCENE_SEARCH = "SEARCH"
	SCENE_DETAIL = "DETAIL"
	SCENE_KANBAN = "KANBAN"

	SCENE_RELATED = "RELATED"
)

// CLICK
const (
	CLICK_BUTTON = "BUTTON" // 列表操作栏
	CLICK_ACTION = "ACTION" // 行内操作列
	CLICK_INLINE = "INLINE" // 行内单元格
)
